/**
 * Export Handlers for TAS Assistant Unit Plans
 *
 * Provides functions to export generated unit plans in multiple formats:
 * - DOCX: Editable Word documents with professional formatting
 * - PDF: Browser-based print to PDF with optimized styles
 * - Markdown: Clean, git-friendly text format
 *
 * All exports include comprehensive plan details formatted appropriately
 * for each output type.
 */

import {
  Document,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  PageBreak,
  TableOfContents,
  Footer,
  Header,
  PageNumber,
  NumberFormat,
} from 'docx';
import { saveAs } from 'file-saver';
import { GeneratedPlan, DeliveryMode } from '@/types/unit-plan';

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Generates a safe filename from plan metadata
 */
function generateFilename(plan: GeneratedPlan, extension: string): string {
  const qualCode = plan.meta.qualification_code || 'PLAN';
  const date = new Date(plan.metadata.generated_at).toISOString().split('T')[0];
  return `TAS-Plan-${qualCode}-${date}.${extension}`;
}

/**
 * Formats delivery mode for display
 */
function formatDeliveryMode(mode: DeliveryMode): string {
  const modes = {
    face_to_face: 'Face-to-Face',
    online: 'Online',
    blended: 'Blended',
  };
  return modes[mode] || mode;
}

/**
 * Formats date for display
 */
function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-AU', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

// ============================================================================
// DOCX Export
// ============================================================================

/**
 * Exports plan as DOCX file
 * Downloads automatically via file-saver
 */
export async function exportToDOCX(
  plan: GeneratedPlan,
  filename?: string
): Promise<void> {
  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            pageNumbers: {
              start: 1,
              formatType: NumberFormat.DECIMAL,
            },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                text: 'TAS Unit Plan',
                alignment: AlignmentType.RIGHT,
                style: 'header',
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: 'Generated by TAS Assistant - Review and customize before use | Page ',
                    size: 18,
                  }),
                  new TextRun({
                    children: [PageNumber.CURRENT],
                    size: 18,
                  }),
                ],
              }),
            ],
          }),
        },
        children: [
          // Title Page
          ...createTitlePage(plan),

          // Table of Contents
          new Paragraph({
            text: 'TABLE OF CONTENTS',
            heading: HeadingLevel.HEADING_1,
            pageBreakBefore: true,
          }),
          new TableOfContents('Table of Contents', {
            hyperlink: true,
            headingStyleRange: '1-3',
          }),

          // Overview Section
          new Paragraph({
            text: '1. Overview',
            heading: HeadingLevel.HEADING_1,
            pageBreakBefore: true,
          }),
          ...createOverviewSection(plan),

          // Cohort Profile Section
          new Paragraph({
            text: '2. Cohort Profile',
            heading: HeadingLevel.HEADING_1,
            pageBreakBefore: true,
          }),
          ...createCohortSection(plan),

          // Weekly Plan Section
          new Paragraph({
            text: '3. Weekly Delivery Plan',
            heading: HeadingLevel.HEADING_1,
            pageBreakBefore: true,
          }),
          ...createWeeklyPlanSection(plan),

          // Units Section
          new Paragraph({
            text: '4. Units of Competency',
            heading: HeadingLevel.HEADING_1,
            pageBreakBefore: true,
          }),
          ...createUnitsSection(plan),

          // Resources Section
          new Paragraph({
            text: '5. Resources & Facilities',
            heading: HeadingLevel.HEADING_1,
            pageBreakBefore: true,
          }),
          ...createResourcesSection(plan),

          // Risks & Assumptions Section
          new Paragraph({
            text: '6. Risks & Assumptions',
            heading: HeadingLevel.HEADING_1,
            pageBreakBefore: true,
          }),
          ...createRisksAssumptionsSection(plan),

          // Compliance Notes
          new Paragraph({
            text: '7. Compliance Notes',
            heading: HeadingLevel.HEADING_1,
            pageBreakBefore: true,
          }),
          ...createComplianceSection(plan),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const fileName = filename || generateFilename(plan, 'docx');
  saveAs(blob, fileName);
}

// DOCX Helper Functions

function createTitlePage(plan: GeneratedPlan): Paragraph[] {
  return [
    new Paragraph({
      text: '',
      spacing: { before: 400, after: 400 },
    }),
    new Paragraph({
      text: 'TAS UNIT PLAN',
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      text: plan.meta.qualification,
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    new Paragraph({
      text: `Qualification Code: ${plan.meta.qualification_code || 'N/A'}`,
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      text: `Generated: ${formatDate(plan.metadata.generated_at)}`,
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      text: `Delivery Mode: ${formatDeliveryMode(plan.meta.delivery_mode)}`,
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      text: `Duration: ${plan.meta.duration_weeks} weeks, ${plan.meta.total_hours} hours`,
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      text: `Confidence Score: ${(plan.confidence * 100).toFixed(0)}%`,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
  ];
}

function createOverviewSection(plan: GeneratedPlan): Paragraph[] {
  return [
    new Paragraph({
      text: 'Plan Metadata',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 100 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Schema Version: ', bold: true }),
        new TextRun(plan.metadata.schema_version),
      ],
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Project Type: ', bold: true }),
        new TextRun(plan.metadata.project_type),
      ],
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Generated: ', bold: true }),
        new TextRun(formatDate(plan.metadata.generated_at)),
      ],
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Confidence Score: ', bold: true }),
        new TextRun(`${(plan.confidence * 100).toFixed(1)}%`),
      ],
      spacing: { after: 200 },
    }),
    new Paragraph({
      text: 'Qualification Details',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 100 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Qualification: ', bold: true }),
        new TextRun(plan.meta.qualification),
      ],
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Code: ', bold: true }),
        new TextRun(plan.meta.qualification_code || 'N/A'),
      ],
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Delivery Mode: ', bold: true }),
        new TextRun(formatDeliveryMode(plan.meta.delivery_mode)),
      ],
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Duration: ', bold: true }),
        new TextRun(`${plan.meta.duration_weeks} weeks`),
      ],
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Total Hours: ', bold: true }),
        new TextRun(`${plan.meta.total_hours} hours`),
      ],
      spacing: { after: 100 },
    }),
  ];
}

function createCohortSection(plan: GeneratedPlan): Paragraph[] {
  return [
    new Paragraph({
      text: plan.meta.cohort_profile,
      spacing: { after: 200 },
    }),
    ...(plan.meta.assessment_preferences && plan.meta.assessment_preferences.length > 0
      ? [
          new Paragraph({
            text: 'Assessment Preferences',
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 200, after: 100 },
          }),
          ...plan.meta.assessment_preferences.map(
            (pref) =>
              new Paragraph({
                text: pref,
                bullet: { level: 0 },
                spacing: { after: 50 },
              })
          ),
        ]
      : []),
  ];
}

function createWeeklyPlanSection(plan: GeneratedPlan): Paragraph[] {
  const paragraphs: Paragraph[] = [];

  plan.weekly_plan.forEach((week) => {
    paragraphs.push(
      new Paragraph({
        text: `Week ${week.week}`,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 200, after: 100 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: 'Hours: ', bold: true }),
          new TextRun(`${week.hours}`),
        ],
        spacing: { after: 100 },
      })
    );

    if (week.topics && week.topics.length > 0) {
      paragraphs.push(
        new Paragraph({
          text: 'Topics',
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 100, after: 50 },
        }),
        ...week.topics.map(
          (topic) =>
            new Paragraph({
              text: topic,
              bullet: { level: 0 },
              spacing: { after: 50 },
            })
        )
      );
    }

    if (week.activities && week.activities.length > 0) {
      paragraphs.push(
        new Paragraph({
          text: 'Activities',
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 100, after: 50 },
        }),
        ...week.activities.map(
          (activity) =>
            new Paragraph({
              text: activity,
              bullet: { level: 0 },
              spacing: { after: 50 },
            })
        )
      );
    }

    if (week.assessments && week.assessments.length > 0) {
      paragraphs.push(
        new Paragraph({
          text: 'Assessments',
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 100, after: 50 },
        }),
        ...week.assessments.map(
          (assessment) =>
            new Paragraph({
              text: `${assessment.title} (${assessment.type}) - Units: ${assessment.units.join(', ')}`,
              bullet: { level: 0 },
              spacing: { after: 50 },
            })
        )
      );
    }
  });

  return paragraphs;
}

function createUnitsSection(plan: GeneratedPlan): (Paragraph | Table)[] {
  const elements: (Paragraph | Table)[] = [];

  // Create units table
  const tableRows: TableRow[] = [
    new TableRow({
      tableHeader: true,
      children: [
        new TableCell({
          children: [
            new Paragraph({
              children: [new TextRun({ text: 'Code', bold: true })],
            }),
          ],
          width: { size: 20, type: WidthType.PERCENTAGE },
        }),
        new TableCell({
          children: [
            new Paragraph({
              children: [new TextRun({ text: 'Title', bold: true })],
            }),
          ],
          width: { size: 40, type: WidthType.PERCENTAGE },
        }),
        new TableCell({
          children: [
            new Paragraph({
              children: [new TextRun({ text: 'Hours', bold: true })],
            }),
          ],
          width: { size: 15, type: WidthType.PERCENTAGE },
        }),
        new TableCell({
          children: [
            new Paragraph({
              children: [new TextRun({ text: 'Delivery', bold: true })],
            }),
          ],
          width: { size: 25, type: WidthType.PERCENTAGE },
        }),
      ],
    }),
  ];

  plan.units.forEach((unit) => {
    tableRows.push(
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ text: unit.code })],
          }),
          new TableCell({
            children: [new Paragraph({ text: unit.title })],
          }),
          new TableCell({
            children: [new Paragraph({ text: unit.hours.toString() })],
          }),
          new TableCell({
            children: [
              new Paragraph({ text: formatDeliveryMode(unit.deliveryMethod) }),
            ],
          }),
        ],
      })
    );
  });

  elements.push(
    new Table({
      rows: tableRows,
      width: {
        size: 100,
        type: WidthType.PERCENTAGE,
      },
      borders: {
        top: { style: BorderStyle.SINGLE, size: 1 },
        bottom: { style: BorderStyle.SINGLE, size: 1 },
        left: { style: BorderStyle.SINGLE, size: 1 },
        right: { style: BorderStyle.SINGLE, size: 1 },
        insideHorizontal: { style: BorderStyle.SINGLE, size: 1 },
        insideVertical: { style: BorderStyle.SINGLE, size: 1 },
      },
    })
  );

  // Add detailed unit information
  elements.push(
    new Paragraph({
      text: 'Unit Details',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 400, after: 100 },
    })
  );

  plan.units.forEach((unit) => {
    elements.push(
      new Paragraph({
        text: `${unit.code}: ${unit.title}`,
        heading: HeadingLevel.HEADING_3,
        spacing: { before: 200, after: 100 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: 'Hours: ', bold: true }),
          new TextRun(`${unit.hours}`),
        ],
        spacing: { after: 50 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: 'Delivery Method: ', bold: true }),
          new TextRun(formatDeliveryMode(unit.deliveryMethod)),
        ],
        spacing: { after: 50 },
      })
    );

    if (unit.weekRange) {
      elements.push(
        new Paragraph({
          children: [
            new TextRun({ text: 'Week Range: ', bold: true }),
            new TextRun(`Weeks ${unit.weekRange[0]}-${unit.weekRange[1]}`),
          ],
          spacing: { after: 50 },
        })
      );
    }

    if (unit.assessmentMethods && unit.assessmentMethods.length > 0) {
      elements.push(
        new Paragraph({
          children: [new TextRun({ text: 'Assessment Methods', bold: true })],
          spacing: { before: 100, after: 50 },
        }),
        ...unit.assessmentMethods.map(
          (method) =>
            new Paragraph({
              text: method,
              bullet: { level: 0 },
              spacing: { after: 50 },
            })
        )
      );
    }

    if (unit.prerequisites && unit.prerequisites.length > 0) {
      elements.push(
        new Paragraph({
          children: [new TextRun({ text: 'Prerequisites', bold: true })],
          spacing: { before: 100, after: 50 },
        }),
        ...unit.prerequisites.map(
          (prereq) =>
            new Paragraph({
              text: prereq,
              bullet: { level: 0 },
              spacing: { after: 50 },
            })
        )
      );
    }
  });

  return elements;
}

function createResourcesSection(plan: GeneratedPlan): Paragraph[] {
  if (!plan.meta.resources || plan.meta.resources.length === 0) {
    return [
      new Paragraph({
        children: [
          new TextRun({
            text: 'No specific resources documented.',
            italics: true,
          }),
        ],
      }),
    ];
  }

  return [
    ...plan.meta.resources.map(
      (resource) =>
        new Paragraph({
          text: resource,
          bullet: { level: 0 },
          spacing: { after: 50 },
        })
    ),
  ];
}

function createRisksAssumptionsSection(plan: GeneratedPlan): Paragraph[] {
  const paragraphs: Paragraph[] = [];

  // Risks
  paragraphs.push(
    new Paragraph({
      text: 'Risks',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 100 },
    })
  );

  if (plan.risks && plan.risks.length > 0) {
    plan.risks.forEach((risk) => {
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${risk.description}`, bold: true }),
            ...(risk.impact
              ? [
                  new TextRun({ text: ` (Impact: ${risk.impact})`, italics: true }),
                ]
              : []),
          ],
          spacing: { before: 100, after: 50 },
        })
      );

      if (risk.mitigation) {
        paragraphs.push(
          new Paragraph({
            text: `Mitigation: ${risk.mitigation}`,
            bullet: { level: 0 },
            spacing: { after: 100 },
          })
        );
      }
    });
  } else {
    paragraphs.push(
      new Paragraph({
        children: [
          new TextRun({
            text: 'No significant risks identified.',
            italics: true,
          }),
        ],
      })
    );
  }

  // Assumptions
  paragraphs.push(
    new Paragraph({
      text: 'Assumptions',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 400, after: 100 },
    })
  );

  if (plan.assumptions && plan.assumptions.length > 0) {
    plan.assumptions.forEach((assumption) => {
      paragraphs.push(
        new Paragraph({
          text: assumption.description,
          bullet: { level: 0 },
          spacing: { after: 50 },
        })
      );

      if (assumption.mitigation) {
        paragraphs.push(
          new Paragraph({
            text: `Validation: ${assumption.mitigation}`,
            bullet: { level: 1 },
            spacing: { after: 100 },
          })
        );
      }
    });
  } else {
    paragraphs.push(
      new Paragraph({
        children: [
          new TextRun({
            text: 'No specific assumptions documented.',
            italics: true,
          }),
        ],
      })
    );
  }

  return paragraphs;
}

function createComplianceSection(plan: GeneratedPlan): Paragraph[] {
  return [
    new Paragraph({
      text: 'Australian RTO Requirements',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 100 },
    }),
    new Paragraph({
      text: 'This plan has been generated to align with Australian RTO standards. Please ensure the following before use:',
      spacing: { after: 100 },
    }),
    new Paragraph({
      text: 'All units are from current training packages',
      bullet: { level: 0 },
      spacing: { after: 50 },
    }),
    new Paragraph({
      text: 'Delivery hours meet nominal hours requirements',
      bullet: { level: 0 },
      spacing: { after: 50 },
    }),
    new Paragraph({
      text: 'Assessment methods align with assessment requirements',
      bullet: { level: 0 },
      spacing: { after: 50 },
    }),
    new Paragraph({
      text: 'Resources and facilities are adequate for delivery',
      bullet: { level: 0 },
      spacing: { after: 50 },
    }),
    new Paragraph({
      text: 'LLN requirements are addressed in cohort profile',
      bullet: { level: 0 },
      spacing: { after: 50 },
    }),
    new Paragraph({
      text: '',
      spacing: { before: 200 },
    }),
    new Paragraph({
      text: 'Important Notes',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 100 },
    }),
    new Paragraph({
      text: 'This plan is AI-generated and should be reviewed by qualified trainers before use. Customize sections to match your specific cohort, resources, and organizational requirements.',
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Confidence Score: ', bold: true }),
        new TextRun(
          `${(plan.confidence * 100).toFixed(1)}% - This indicates the AI's confidence in the plan structure and content.`
        ),
      ],
      spacing: { after: 100 },
    }),
  ];
}

// Import Packer for DOCX generation
import { Packer } from 'docx';

// ============================================================================
// PDF Export
// ============================================================================

/**
 * Triggers browser print dialog for PDF export
 * Applies print-optimized styles
 */
export function exportToPDF(): Promise<void> {
  return new Promise((resolve) => {
    // Apply print-friendly class to body if not already present
    const printClass = 'tas-print-mode';
    document.body.classList.add(printClass);

    // Trigger print dialog
    window.print();

    // Clean up after print dialog closes
    // Use setTimeout to allow print dialog to fully close
    setTimeout(() => {
      document.body.classList.remove(printClass);
      resolve();
    }, 1000);
  });
}

// ============================================================================
// Markdown Export
// ============================================================================

/**
 * Exports plan as Markdown file
 * Downloads automatically
 */
export function exportToMarkdown(
  plan: GeneratedPlan,
  filename?: string
): void {
  const markdown = generateMarkdown(plan);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const fileName = filename || generateFilename(plan, 'md');
  saveAs(blob, fileName);
}

/**
 * Generates markdown content from plan
 */
function generateMarkdown(plan: GeneratedPlan): string {
  const lines: string[] = [];

  // YAML frontmatter
  lines.push('---');
  lines.push(`title: "TAS Unit Plan - ${plan.meta.qualification}"`);
  lines.push(`qualification_code: "${plan.meta.qualification_code || 'N/A'}"`);
  lines.push(`generated: "${plan.metadata.generated_at}"`);
  lines.push(`delivery_mode: "${plan.meta.delivery_mode}"`);
  lines.push(`duration_weeks: ${plan.meta.duration_weeks}`);
  lines.push(`total_hours: ${plan.meta.total_hours}`);
  lines.push(`confidence: ${plan.confidence}`);
  lines.push('---');
  lines.push('');

  // Title
  lines.push(`# TAS Unit Plan: ${plan.meta.qualification}`);
  lines.push('');

  // Metadata
  lines.push('## Overview');
  lines.push('');
  lines.push(`**Generated:** ${formatDate(plan.metadata.generated_at)}`);
  lines.push(`**Qualification Code:** ${plan.meta.qualification_code || 'N/A'}`);
  lines.push(`**Delivery Mode:** ${formatDeliveryMode(plan.meta.delivery_mode)}`);
  lines.push(`**Duration:** ${plan.meta.duration_weeks} weeks, ${plan.meta.total_hours} hours`);
  lines.push(`**Confidence Score:** ${(plan.confidence * 100).toFixed(1)}%`);
  lines.push('');

  // Cohort Profile
  lines.push('## Cohort Profile');
  lines.push('');
  lines.push(plan.meta.cohort_profile);
  lines.push('');

  if (plan.meta.assessment_preferences && plan.meta.assessment_preferences.length > 0) {
    lines.push('### Assessment Preferences');
    lines.push('');
    plan.meta.assessment_preferences.forEach((pref) => {
      lines.push(`- ${pref}`);
    });
    lines.push('');
  }

  // Weekly Plan
  lines.push('## Weekly Delivery Plan');
  lines.push('');

  plan.weekly_plan.forEach((week) => {
    lines.push(`### Week ${week.week}`);
    lines.push('');
    lines.push(`**Hours:** ${week.hours}`);
    lines.push('');

    if (week.topics && week.topics.length > 0) {
      lines.push('**Topics:**');
      week.topics.forEach((topic) => {
        lines.push(`- ${topic}`);
      });
      lines.push('');
    }

    if (week.activities && week.activities.length > 0) {
      lines.push('**Activities:**');
      week.activities.forEach((activity) => {
        lines.push(`- ${activity}`);
      });
      lines.push('');
    }

    if (week.assessments && week.assessments.length > 0) {
      lines.push('**Assessments:**');
      week.assessments.forEach((assessment) => {
        lines.push(`- **${assessment.title}** (${assessment.type})`);
        lines.push(`  - Units: ${assessment.units.join(', ')}`);
        if (assessment.notes) {
          lines.push(`  - Notes: ${assessment.notes}`);
        }
      });
      lines.push('');
    }
  });

  // Units
  lines.push('## Units of Competency');
  lines.push('');
  lines.push('| Code | Title | Hours | Delivery | Week Range |');
  lines.push('|------|-------|-------|----------|------------|');

  plan.units.forEach((unit) => {
    const weekRange = unit.weekRange
      ? `${unit.weekRange[0]}-${unit.weekRange[1]}`
      : 'N/A';
    lines.push(
      `| ${unit.code} | ${unit.title} | ${unit.hours} | ${formatDeliveryMode(
        unit.deliveryMethod
      )} | ${weekRange} |`
    );
  });
  lines.push('');

  // Unit Details
  lines.push('### Unit Details');
  lines.push('');

  plan.units.forEach((unit) => {
    lines.push(`#### ${unit.code}: ${unit.title}`);
    lines.push('');
    lines.push(`- **Hours:** ${unit.hours}`);
    lines.push(`- **Delivery Method:** ${formatDeliveryMode(unit.deliveryMethod)}`);

    if (unit.weekRange) {
      lines.push(`- **Week Range:** Weeks ${unit.weekRange[0]}-${unit.weekRange[1]}`);
    }

    if (unit.assessmentMethods && unit.assessmentMethods.length > 0) {
      lines.push('- **Assessment Methods:**');
      unit.assessmentMethods.forEach((method) => {
        lines.push(`  - ${method}`);
      });
    }

    if (unit.prerequisites && unit.prerequisites.length > 0) {
      lines.push('- **Prerequisites:**');
      unit.prerequisites.forEach((prereq) => {
        lines.push(`  - ${prereq}`);
      });
    }

    lines.push('');
  });

  // Resources
  lines.push('## Resources & Facilities');
  lines.push('');

  if (plan.meta.resources && plan.meta.resources.length > 0) {
    plan.meta.resources.forEach((resource) => {
      lines.push(`- ${resource}`);
    });
  } else {
    lines.push('*No specific resources documented.*');
  }
  lines.push('');

  // Risks
  lines.push('## Risks');
  lines.push('');

  if (plan.risks && plan.risks.length > 0) {
    plan.risks.forEach((risk) => {
      const impact = risk.impact ? ` (Impact: **${risk.impact}**)` : '';
      lines.push(`- **${risk.description}**${impact}`);
      if (risk.mitigation) {
        lines.push(`  - Mitigation: ${risk.mitigation}`);
      }
    });
  } else {
    lines.push('*No significant risks identified.*');
  }
  lines.push('');

  // Assumptions
  lines.push('## Assumptions');
  lines.push('');

  if (plan.assumptions && plan.assumptions.length > 0) {
    plan.assumptions.forEach((assumption) => {
      lines.push(`- ${assumption.description}`);
      if (assumption.mitigation) {
        lines.push(`  - Validation: ${assumption.mitigation}`);
      }
    });
  } else {
    lines.push('*No specific assumptions documented.*');
  }
  lines.push('');

  // Compliance Notes
  lines.push('## Compliance Notes');
  lines.push('');
  lines.push('### Australian RTO Requirements');
  lines.push('');
  lines.push(
    'This plan has been generated to align with Australian RTO standards. Please ensure:'
  );
  lines.push('');
  lines.push('- All units are from current training packages');
  lines.push('- Delivery hours meet nominal hours requirements');
  lines.push('- Assessment methods align with assessment requirements');
  lines.push('- Resources and facilities are adequate for delivery');
  lines.push('- LLN requirements are addressed in cohort profile');
  lines.push('');

  lines.push('### Important Notes');
  lines.push('');
  lines.push(
    'This plan is AI-generated and should be reviewed by qualified trainers before use. Customize sections to match your specific cohort, resources, and organizational requirements.'
  );
  lines.push('');
  lines.push(
    `**Confidence Score:** ${(plan.confidence * 100).toFixed(
      1
    )}% - This indicates the AI's confidence in the plan structure and content.`
  );
  lines.push('');

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by TAS Assistant - Review and customize before use*');
  lines.push('');

  return lines.join('\n');
}
